### ISSUE TITLE
請教，如果要一個view顯示兩個或多個圖的item，求指導

### ISSUE THREAD

**Issue by oliguo** [lightSky/InfiniteIndicator#1]
嘗試成功運行了項目，想舉一反三，想要一個view顯示兩個或多個圖的item，并對於點擊響應，
大概思路：
1.copy new layout from render_type_default.xml to more_render_type_default.xml,
more_render_type_default.xml add one imageView:
code:
https://github.com/oliguo/InfiniteIndicator/blob/master/library/src/main/res/layout/more_render_type_default.xml

2.create MoreSliderView extends BaseSliderView,and override getView:
code:
https://github.com/oliguo/InfiniteIndicator/blob/master/library/src/main/java/cn/lightsky/infiniteindicator/slideview/MoreSliderView.java

3.add new indicator in activity_anim_indicator.xml
code:
https://github.com/oliguo/InfiniteIndicator/blob/master/demo/src/main/res/layout/activity_anim_indicator.xml

4.add indicator object in AnimIndicatorActivity.java
code:
https://github.com/oliguo/InfiniteIndicator/blob/master/demo/src/main/java/cn/lightsky/infiniteindicator/AnimIndicatorActivity.java

執行安裝后，不能開啟，請教下是不是哪裡寫錯了

**Comment by lightSky** [comment]
这个特性暂不支持哈，完全是另一种效果，一个页面多条目再加上indicator会比较怪哇，你说的这种效果还是挺多的，简单的可以通过RecycleView来做
