### ISSUE TITLE
Need a method to clear and recreate InfiniteIndicatorLayout

### ISSUE THREAD

**Issue by mdtuyen** [lightSky/InfiniteIndicator#17]
I see that in adapter this library have method to remove all slider but in InfiniteIndicatorLayout have not method to implement it.

**Comment by lightSky** [comment]
Yes，You want to remove all sliders or update them ? I will add the update sliders method on the next version ,also I will support the remove all interface.

**Comment by lituanzhang** [comment]
I attempt to reset the slider by removeAllViews(), then re-add it, but the slider shows nothing. what is the right method reset it ?

**Comment by lightSky** [comment]
Now 1.1.0 is release，it support auto updae,just use addPages is work.
