### ISSUE TITLE
轮播问题

### ISSUE THREAD

**Issue by Kenmmm** [lightSky/InfiniteIndicator#18]
放在viewpager中，自动轮播到了两头之后，不会继续轮播。
从网络获取图片之后就算调用startAutoScoll，也不会轮播。手动滑一下，便会自动轮播。。。

**Comment by Kenmmm** [comment]
现在唯一的问题就是进去之后必须手动滑一下才可以自动滑动。。。

**Comment by lightSky** [comment]
你在代码里明确调用startAutoScroll也不行么？

**Comment by Kenmmm** [comment]
在onResume里面写了，不行，必须手滑一下才可以，但是看demo的话是一样的，不知道是不是在Fragment里面的原因
