### ISSUE TITLE
I got into trouble.

### ISSUE THREAD

**Issue by JackDinealKIM** [lightSky/InfiniteIndicator#19]
When I compile this below error shown

Error:Could not find any matches for com.nineoldandroids:library:2.4.+ as no versions of com.nineoldandroids:library are available.
Required by:
    Finlandia:app:unspecified > cn.lightsky.infiniteindicator:library:1.0.3
<a href="searchInBuildFiles">Search in build.gradle files</a>

When I figure out. there is a gradle dependency problem.

your one is like this. "compile 'com.nineoldandroids:library:2.4.+'

after error my one changed like this without +

"compile 'com.nineoldandroids:library:2.4.0'

It works fine. please check this issue. Thanks.

**Comment by lightSky** [comment]
Thanks for your feedback.I solved it ,and now 1.0.5 is available.But the really reason I still need to find.
