### ISSUE TITLE
突然就出现Error:Failed to resolve: com.nineoldandroids:library:2.4.+

### ISSUE THREAD

**Issue by imyyq-star** [lightSky/InfiniteIndicator#20]
你好，我之前一直在用你的项目，使用compile 'cn.lightsky.infiniteindicator:library:1.0.3'，但是我今天打开我的项目后发现如下错误：
Error:Failed to resolve: com.nineoldandroids:library:2.4.+
<a href="openFile:E:/AndroidStudio/SaoHeMerchant/app/build.gradle">Open File</a><br><a href="open.dependency.in.project.structure">Show in Project Structure dialog</a>

然后我重新编译：发现错误
Error:A problem occurred configuring project ':app'.

> Could not resolve all dependencies for configuration ':app:_debugCompile'.
> Could not find any matches for com.nineoldandroids:library:2.4.+ as no versions of com.nineoldandroids:library are available.
>      Searched in the following locations:
>          https://jcenter.bintray.com/com/nineoldandroids/library/maven-metadata.xml
>          https://jcenter.bintray.com/com/nineoldandroids/library/
>          file:/E:/Program Files/sdk/extras/android/m2repository/com/nineoldandroids/library/maven-metadata.xml
>          file:/E:/Program Files/sdk/extras/android/m2repository/com/nineoldandroids/library/
>          file:/E:/Program Files/sdk/extras/google/m2repository/com/nineoldandroids/library/maven-metadata.xml
>          file:/E:/Program Files/sdk/extras/google/m2repository/com/nineoldandroids/library/
>      Required by:
>          SaoHeMerchant:app:unspecified > cn.lightsky.infiniteindicator:library:1.0.3

**Comment by 397183560** [comment]
遇到相同情况，怀疑是Android studio升级或sdk升级影响。com.nineoldandroids:library:2.4.+改成
com.nineoldandroids:library:2.4  ？？

**Comment by lightSky** [comment]
@397183560 你的方式是对的，可以改成 'com.nineoldandroids:library:2.4.0'

**Comment by imyyq-star** [comment]
@lightSky  我一开始是引用Module的方式，后来改成compile 'cn.lightsky.infiniteindicator:library:1.0.3'的方式，所以无法更改里面的东西，为了迅速解决问题，我改成引用一开始Module里的aar文件

**Comment by lightSky** [comment]
赞，是的，快速解决问题才是王道，我待会更新下到1.0.4

**Comment by iPeng** [comment]
@lightSky 尝试自己改，没有成功。现在有1.0.4了吗？

**Comment by lightSky** [comment]
@iPeng 1.0.5 可以用了
