### ISSUE TITLE
重置slider失败问题反馈，谢谢

### ISSUE THREAD

**Issue by lituanzhang** [lightSky/InfiniteIndicator#22]
我利用三个方法mSlider.removeAllViews()、mSlider.refreshDrawableState()、mSlider.notifyDataChange()成功清除了之前加载的sliderview，但是再利用 mSlider.addSlider(sliderView)添加原来的sliderView时就什么也不显示了，很奇怪，楼主什么时候有空看一下，给一个正确的方法吧

**Comment by lightSky** [comment]
之前没有update的方法，目前在重构，实现上做了优化，已经最后阶段，后在这几天放出，要是不急，可以使用新版

**Comment by lituanzhang** [comment]
谢谢楼主回馈，翘首以待

**Comment by lightSky** [comment]
新版本已经放出来了，可以使用最新的1.1.0 试试
