### ISSUE TITLE
支持自定义 page

### ISSUE THREAD

**Issue by baitouwei** [lightSky/InfiniteIndicator#25]
现在每个 page 页面比较固定，只能显示一张图片，有考虑支持自定义 page 页面吗？

**Comment by xiaomeixw** [comment]
必须自定义page啊，否则没办法玩啊~~如果是这个界面传递对象过去，用现在封装的page完全不行....

**Comment by lightSky** [comment]
最新版本支持了，可以通过自定义VIewBinder，复写getView方法，类似Adapter的getView方法
