### ISSUE TITLE
ImageView centerCrop

### ISSUE THREAD

**Issue by borjaruiz** [lightSky/InfiniteIndicator#27]
Is it possible to scale imageView to not deforming it?

What I need is the pager with a wrap_content height equals to image height.

**Comment by xiaomeixw** [comment]
need Modify source code：
simple_slider_view.xml

**Comment by lightSky** [comment]
The latest version support custome viewBinder，you can do anything you want as the getView of Adapter.Thank your answer @xiaomeixw  ^_^
