### ISSUE TITLE
一些描述性小问题

### ISSUE THREAD

**Issue by shuaisunny** [lightSky/InfiniteIndicator#28]
帅，下载代码试用过程中遇到的小细节问题
1、demo 的test 文件夹中addSlidersActivity.java ---->AddSlidersActivity.java
2、ReadMind中，Usage描述中，Layout描述InfiniteIndicatorLayout(老版本)--->InfiniteIndicator
谢谢你

**Comment by xiaomeixw** [comment]
+1

**Comment by lightSky** [comment]
感谢反馈啊，新的版本已修复了
