### ISSUE TITLE
Can not slide up and down in scrollview！！！

### ISSUE THREAD

**Issue by yushilong** [lightSky/InfiniteIndicator#4]

**Comment by OptimusPrimeRen** [comment]
Change Code.  In class -----cn.lightsky.infiniteindicator.InfiniteIndicatorLayout.     Chage dispatchTouchEvent method,remove the last getParent().requestDisallowInterceptTouchEvent(true).   I am from China,English is not very good,hope you can read.

**Comment by lightSky** [comment]
@OptimusPrimeRen +1:  但是我想说一句，咱们都是大陆的 :)

**Comment by yushilong** [comment]
@OptimusPrimeRen 我也是中国人，哈哈！

**Comment by OptimusPrimeRen** [comment]
你好，哈哈哈。请问你现在还在搞Android吗？

**Comment by OptimusPrimeRen** [comment]
@yushilong 你好，哈哈哈。请问你现在还在搞Android吗？粗略看了下你的github，好像很厉害了啊！

**Comment by yushilong** [comment]
@OptimusPrimeRen 对啊，还在搞Android，养家糊口!

**Comment by OptimusPrimeRen** [comment]
@yushilong  大神啊，能给个微信或者qq吗？相识也是缘分，以后有问题还想请教你啊。

**Comment by OptimusPrimeRen** [comment]
@lightSky   那请问你有改了哪里来解决这个问题吗？你最新的代码好像不是我使用的那种方式纠正的啊？

**Comment by lightSky** [comment]
@OptimusPrimeRen 你的方式是可以的，只是最近可能还要修复其它bug，到时候统一提交，所以还需要过几天再更新
