### ISSUE TITLE
拉不到库

### ISSUE THREAD

**Issue by jarain** [lightSky/InfiniteIndicator#5]
Error:(5, 13) Failed to resolve: cn.lightsky.infiniteindicator:library:1.0.1

**Comment by lightSky** [comment]
刚测了一遍，可以，检查你的gradle是否是离线状态，File->Settings->Gradle "Offline work"  ，如果是，去掉勾

**Comment by jarain** [comment]
查了一下，可能是com.android.tools.build的原因，正在升级，谢谢回复！
我在网站上搜了一下，可以找到这个包。

**Comment by jarain** [comment]
<com.lightsky.infiniteindicator.InfiniteIndicatorLayout
        android:id="@+id/indicator_default_circle"
        app:indicator_type="indicator_anim_circle"
        android:layout_height="wrap_content"
        android:layout_weight="match_parent"/>

发现个小问题 例子里面：android:layout_weight="match_parent"

**Comment by lightSky** [comment]
哈哈，手误了，谢谢

**Comment by yasenagat** [comment]
拉不到库，请问什么原因？
classpath 'com.android.tools.build:gradle:1.2.3'
Offline work ，没有钩。

**Comment by lightSky** [comment]
@yasenagat 还拉不到么？你的错误信息太模糊了，可以贴具体点

**Comment by yasenagat** [comment]
@jarain 拉不到库，请问是如何解决的？
@lightSky copy compile 'cn.lightsky.infiniteindicator:library:1.0.1' 这句话后，sync成功了，没有报错，但是库还是木有呀，好奇怪呀，感觉是我的项目有问题，但是还不知道具体什么原因。
new 一个 project，可以拉倒库。。。

**Comment by lightSky** [comment]
拉到就好

**Comment by yasenagat** [comment]
打算用的项目也拉倒库了，具体方法，是把gradle的设置有重新点选了一遍，然后重启，清除各种缓存。
不过你这个minSDK是11，我的是8。。。这。。。

**Comment by lightSky** [comment]
之前写的有点随意了，刚才改了minSdkVersion ＝8 ，已经上传到maven，版本号1.0.2 。不过还没测试，所以Github上暂时不更新，但你可以拉到1.0.2的版本

**Comment by yasenagat** [comment]
@lightSky OK,试一下
