### ISSUE TITLE
图片切换，每次都读取URL的图片，没有缓存

### ISSUE THREAD

**Issue by yasenagat** [lightSky/InfiniteIndicator#9]
手动滑动切换时，loading有点长，
不能设置默认的图片，比如loading中显示的默认图片，还有读取图片失败显示的图片
建议把addSlider，改成或者添加 ，一个addCustomView的功能，就可以了，具体的view由用户自己创建。
图片读取缓存问题，让用户自己处理，只负责切换自动切换view。
并且提供onPageChangeListener

**Comment by lightSky** [comment]
一：loading的默认图片，失败图片都有API的  

``` java
 DefaultSliderView textSliderView = new DefaultSliderView(this);
            textSliderView
                    .image(url_maps.get(name))
                    .setScaleType(BaseSliderView.ScaleType.Fit)
                    .showImageResForEmpty(R.drawable.img_default)
                    .showImageResForError(R.drawable.img_error)
                    .setOnSliderClickListener(this);
```

二：具体的View是支持自定义的
DefaultSliderView只是提供了一个实现SliderView的默认实现，你可以参考它，自己自定义PageView

三：onPageChangeListener暂未支持
这个功能在下一个版本中支持，你可以在InfiniteIndicatorLayout类中添加一个方法

``` java
 public void setOnPageChangeListener(ViewPager.OnPageChangeListener onPageChangeListener){
            mIndicator.setOnPageChangeListener(onPageChangeListener);
    }
```

四 缓存
内部集成了第三方的图片加载库Picasso，图片缓存的一整套的流程已经有的。这里默认也是支持的，可以参考Picasso文档
